spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show_sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  devtools:
    add-properties: false

mail:
  active: true
