spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: OBA_ADMIN
    password: OBA_LOCAL
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show_sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  devtools:
    add-properties: false

mail:
  active: true
