INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (1,'','Nova Escola','https://novaescola.org.br'),
	 (2,'','Universidade Estadual de Campinas (Unicamp)','http://m3.ime.unicamp.br/'),
	 (3,'','Universidade Federal do Rio Grande do Sul (UFRGS)','http://mdmat.mat.ufrgs.br/'),
	 (4,'','Universidade de Aveiro - Portugal','http://portal.ua.pt/cibermat.asp'),
	 (5,'','Rede Interativa Virtual de Informação (Rived)','http://rived.mec.gov.br/'),
	 (6,'','Professor Gilmar Bonatto','http://sites.google.com/site/gilmaths/'),
	 (7,'','Centro Universitário São Francisco','http://sites.unifra.br/'),
	 (8,'','Fundação CECIERJ (Fundação Centro de Ciências e Educação Superior à Distância do Estado do Rio de Janeiro)','http://teca.cecierj.edu.br/'),
	 (9,'','Centro de Competência da CERCIFAF','http://www.cercifaf.org.pt'),
	 (10,'','Educação Dinâmica','http://www.educacaodinamica.com.br/');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (11,'','Educommatica','http://www.educommatica.com.br/'),
	 (12,'','Secretaria Municipal da Educação do Rio de Janeiro (SME-RJ) EDUCOPÉDIA','http://www.educopedia.com.br/'),
	 (13,'marco@eidosk.com','Eidosk','http://www.eidosk.com/'),
	 (14,'','Abril Educação','http://www.elemento9.com.br/'),
	 (15,'genmagic@gmail.com','Genmagic','http://www.genmagic.net/'),
	 (16,'','Universidade Estadual de Campinas. Grupo Gestor de Tecnologias Educacionais','http://www.ggte.unicamp.br'),
	 (17,'','Gringene Bioinformatics','http://www.gringene.org/'),
	 (18,'','HypatiaMat (Universidade do Minho e Univerisdade de Coimbra)','http://www.hypatiamat.com/'),
	 (19,'','Imagem.eti','http://www.imagem.eti.br/'),
	 (20,'josephmcarney@gmail.com/','Joseph M. Carney','http://www.josephmcarney.com/');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (21,'','Math Playground LLC','http://www.mathplayground.com/'),
	 (22,'','Mídias Educativas','http://www.midiaseducativas.com.br'),
	 (23,'','Núcleo de Desenvolvimento de Objetos de Aprendizagem Significativa (NOAS)','http://www.noas.com.br'),
	 (24,'','Pingado Sociedade Ilustrativa','http://www.pingado.com/'),
	 (25,'','Grupo de Pesquisa e Produção de Ambientes Interativos e Objetos de Aprendizagem (Proativa) da Universidade Federal do Ceará (UFC)','http://www.proativa.vdl.ufc.br/'),
	 (26,'','Professor Cardy Meier','http://www.profcardy.com/'),
	 (27,'','Laboratório Virutal de Matemática da Universidade Regional do Noroeste do Estado do Rio Grande do Sul (UNIJUÍ)','http://www.projetos.unijui.edu.br'),
	 (28,'tmichel@unijui.edu.br','Universidade Regional do Noroeste do Estado do Rio Grande do Sul (UNIJUÍ) em parceria com o Núcleo de Tecnologias Educacionais (NTE) de Ijuí e RIVED/SEE/MEC','http://www.projetos.unijui.edu.br/matematica/'),
	 (29,'','Universidade Regional do Noroeste do Estado do Rio Grande do Sul (UNIJUÍ)','http://www.projetos.unijui.edu.br/matematica/fabrica_virtual/'),
	 (30,'','Sioux','http://www.sioux.com.br/');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (31,'','Soplaar.com','http://www.soplaar.com/'),
	 (32,'','Grupo de Pesquisa em Objetos de Aprendizagem de Matemátia nos laboratórios do Instituto de Ciências Matemáticas e de Computação (ICMC) da Universidade de São Paulo (USP) campus de São Carlos','http://www.tsampaio.com/ic/'),
	 (33,'','Universidade Federal Fluminense (UFF)','http://www.uff.br/cdme/'),
	 (34,'','Grupo Virtuous Tecnologia Educacional','http://www.virtuous.com.br/'),
	 (35,'','O Laboratório Didático Virtual (LabVirt) da Universidade de São Paulo (USP)','http://www2.fe.usp.br/~mef-pietro/rived/#'),
	 (36,'','Centro Universitário São Francisco e Universidade Federal de Santa Maria (UFSM)','http://wwww.unifra.br/site'),
	 (37,'','Gabriele Cirulli','https://gabrielecirulli.com/'),
	 (38,'','PhET Interactive Simulations - University of Colorado','https://phet.colorado.edu/pt_BR/'),
	 (39,'','Khan Academy','https://pt.khanacademy.org'),
	 (40,'','Tiago Serafim e Vinicius Serafim','https://rachacuca.com.br/');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (41,'','Professor Gilmar Bonatto','https://sites.google.com/site/gilmaths/GilMaths'),
	 (42,'','Funbrain','https://www.funbrain.com'),
	 (43,'','GeoGebra - Dynamic Mathematics for Everyone','https://www.geogebra.org/'),
	 (44,'','Steve Phelps','https://www.geogebra.org/stevephelps'),
	 (45,'','Mangahigh','https://www.mangahigh.com/'),
	 (46,'','Ilustração e Programação - Pingado Sociedade Ilustrativa','www.pingado.com'),
	 (47,'','Universidade Federal de Uberlândia (UFU) e Rede Interativa Virtual de Educação (Rived)','http://www.rived.ufu.br/'),
	 (48,'','Mariana Caltabiano Criações','https://iguinho.com.br/'),
	 (49,'','Fabrico para a Agência Nacional de Águas - ANA','http://dtcom.com.br/#sobre'),
	 (50,'','Daniel Kraft','');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (51,'','Michael Totschnig','https://play.google.com/store/apps/developer?id=Michael+Totschnig'),
	 (52,'','Nadya Khokhlova','https://play.google.com/store/apps/developer?id=Nadya+Khokhlova'),
	 (53,'','NSC Co.','https://play.google.com/store/apps/developer?id=NSC+Co.'),
	 (54,'','UpGado',''),
	 (55,'','Wjj Studio','https://play.google.com/store/apps/developer?id=Wjj+Studio'),
	 (56,'','Zacharias Hadjilambrou','https://play.google.com/store/apps/developer?id=Zacharias+Hadjilambrou'),
	 (57,'','Abhishek Malpani','https://play.google.com/store/apps/developer?id=Abhishek+Malpani'),
	 (58,'','AI Factory Limited','https://play.google.com/store/apps/developer?id=AI+Factory+Limited'),
	 (59,'','Andrey_Stepanov','https://play.google.com/store/apps/developer?id=Andrey_Stepanov'),
	 (60,'','Antoni','https://play.google.com/store/apps/developer?id=Antoni');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (61,'','App2eleven','https://play.google.com/store/apps/developer?id=App2eleven'),
	 (62,'','applabs','https://play.google.com/store/apps/developer?id=applabs'),
	 (63,'','Artyom Safonov','https://play.google.com/store/apps/developer?id=Artyom+Safonov'),
	 (64,'','Asteroid Games 3D','https://play.google.com/store/apps/developer?id=Asteroid+GameS+3D'),
	 (65,'','Avsey','https://play.google.com/store/apps/developer?id=Avsey'),
	 (66,'','Ben Buxton','https://play.google.com/store/apps/developer?id=Ben+Buxton'),
	 (67,'','BitMango','https://play.google.com/store/apps/developer?id=BitMango'),
	 (68,'','Brain Training','https://play.google.com/store/apps/developer?id=Brain+Training'),
	 (69,'','BuildMan','https://play.google.com/store/apps/developer?id=BuildMan'),
	 (70,'','CLNTgames','https://play.google.com/store/apps/developer?id=CLNTgames');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (71,'','Codejuggler','https://play.google.com/store/apps/developer?id=Codejuggler'),
	 (72,'','Cogeon','https://play.google.com/store/apps/developer?id=Cogeon'),
	 (73,'','dapoApps','https://play.google.com/store/apps/developer?id=dapoApps'),
	 (74,'','DemonDreams','https://play.google.com/store/apps/developer?id=DemonDreams'),
	 (75,'','digiplex.in',''),
	 (76,'','Digit Grove','https://play.google.com/store/apps/developer?id=Digit+Grove'),
	 (77,'','Divisi0n.com','https://play.google.com/store/apps/developer?id=Divisi0n.com'),
	 (78,'','Dream Beyond Limit tech pvt ltd',''),
	 (79,'','E7 Mobile','https://play.google.com/store/apps/developer?id=E7+Mobile'),
	 (80,'','EastStudio','https://play.google.com/store/apps/developer?id=EastStudio');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (81,'','Editora W Ltda',''),
	 (82,'','Educacross',''),
	 (83,'','Ejelta LLC','https://play.google.com/store/apps/developer?id=Ejelta+LLC'),
	 (84,'','ELVES GAMES SIA','https://play.google.com/store/apps/developer?id=ELVES+GAMES+SIA'),
	 (85,'','Erpelstolz','https://play.google.com/store/apps/developer?id=Erpelstolz'),
	 (86,'','EscapeGamesFun','https://play.google.com/store/apps/developer?id=EscapeGamesFun'),
	 (87,'','Evgeny Karavashkin','https://play.google.com/store/apps/developer?id=Evgeny+Karavashkin'),
	 (88,'','FBF Sistemas','https://play.google.com/store/apps/developer?id=FBF+Sistemas'),
	 (89,'','FGL Indie Showcase','https://play.google.com/store/apps/developer?id=FGL+Indie+Showcase'),
	 (90,'','Fizze','https://play.google.com/store/apps/developer?id=Fizze');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (91,'','Fly-Studio','https://play.google.com/store/apps/developer?id=Fly-Studio'),
	 (92,'','FTH Games','https://play.google.com/store/apps/developer?id=FTH+Games'),
	 (93,'','FullSizeGames','https://play.google.com/store/apps/developer?id=FullSizeGames'),
	 (94,'','Futuready Media','https://play.google.com/store/apps/developer?id=Futuready+Media'),
	 (95,'','Gamma Play','https://play.google.com/store/apps/developer?id=Gamma+Play'),
	 (96,'','Geckonization','https://play.google.com/store/apps/developer?id=Geckonization'),
	 (97,'','GK apps',''),
	 (98,'','Gram Games','https://play.google.com/store/apps/developer?id=Gram+Games'),
	 (99,'','Gunnar Andersson',''),
	 (100,'','happiapps','https://play.google.com/store/apps/developer?id=happiapps');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (101,'','Happy Baby Games - Free Preschool Educational Apps','https://play.google.com/store/apps/developer?id=Happy+Baby+Games+-+Free+Preschool+Educational+Apps'),
	 (102,'','Herbert Law','https://play.google.com/store/apps/developer?id=Herbert+Law'),
	 (103,'','hiBrett','https://play.google.com/store/apps/developer?id=hiBrett'),
	 (104,'','Hippo Kids Games','https://play.google.com/store/apps/developer?id=Hippo+Kids+Games'),
	 (105,'','HORIS INTERNATIONAL LIMITED','https://play.google.com/store/apps/developer?id=HORIS+INTERNATIONAL+LIMITED'),
	 (106,'','HyperDimSoft','https://play.google.com/store/apps/developer?id=HyperDimSoft'),
	 (107,'','Innopia Games','https://play.google.com/store/apps/developer?id=Innopia+Games'),
	 (108,'','InterAction Education LLC','https://play.google.com/store/apps/developer?id=InterAction+Education+LLC'),
	 (109,'','Internacional Geogebra Institute',''),
	 (110,'','International GeoGebra Institute','https://play.google.com/store/apps/developer?id=International+GeoGebra+Institute');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (111,'','Isr Studio',''),
	 (112,'','Iyoda','https://play.google.com/store/apps/developer?id=Iyoda'),
	 (113,'','James Bruckner','https://play.google.com/store/apps/developer?id=James+Bruckner'),
	 (114,'','Jan Rychtář','https://play.google.com/store/apps/developer?id=Jan+Rychtář'),
	 (115,'','Ketchapp','https://play.google.com/store/apps/developer?id=Ketchapp'),
	 (116,'','Kill Some Time Games','https://play.google.com/store/apps/developer?id=Kill+Some+Time+Games'),
	 (117,'','kittoworks','https://play.google.com/store/apps/developer?id=kittoworks'),
	 (118,'','Ktpsoft','https://play.google.com/store/apps/developer?id=Ktpsoft'),
	 (119,'','LemonClip','https://play.google.com/store/apps/developer?id=LemonClip'),
	 (120,'','Leo De Sol Games','https://play.google.com/store/apps/developer?id=Leo+De+Sol+Games');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (121,'','Levsky','https://play.google.com/store/apps/developer?id=Levsky'),
	 (122,'','LipApps',''),
	 (123,'','LogicalCell_INU','https://play.google.com/store/apps/developer?id=LogicalCell_INU'),
	 (124,'','LR Studios','https://play.google.com/store/apps/developer?id=LR+Studios'),
	 (125,'','M Jack',''),
	 (126,'','Math Underground','https://play.google.com/store/apps/developer?id=Math+Underground'),
	 (127,'','Mathlab Apps, LLC',''),
	 (128,'','Mathway','https://play.google.com/store/apps/developer?id=Mathway'),
	 (129,'','Mikhail Gribkov','https://play.google.com/store/apps/developer?id=Mikhail+Gribkov'),
	 (130,'','MildMania','https://play.google.com/store/apps/developer?id=MildMania');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (131,'','Milux','https://play.google.com/store/apps/developer?id=Milux'),
	 (132,'','Minikler Öğreniyor','https://play.google.com/store/apps/developer?id=Minikler+Öğreniyor'),
	 (133,'','Mobixee Ltd',''),
	 (134,'','Mojo Forest','https://play.google.com/store/apps/developer?id=Mojo+Forest'),
	 (135,'','Morgade Soft','https://play.google.com/store/apps/developer?id=Morgade+Soft'),
	 (136,'','Morsakabi','https://play.google.com/store/apps/developer?id=Morsakabi'),
	 (137,'','Nebula Bytes','https://play.google.com/store/apps/developer?id=Nebula+Bytes'),
	 (138,'','Nitako Brain Puzzles','https://play.google.com/store/apps/developer?id=Nitako+Brain+Puzzles'),
	 (139,'','NixGame','https://play.google.com/store/apps/developer?id=NixGame'),
	 (140,'','Nostopsign, Inc.','https://play.google.com/store/apps/developer?id=Nostopsign,+Inc.');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (141,'','Nulligma','https://play.google.com/store/apps/developer?id=Nulligma'),
	 (142,'','OMC (One Man Creativity)',''),
	 (143,'','Pavans Group Techsoft Pvt. Ltd.','https://play.google.com/store/apps/developer?id=Pavans+Group+Techsoft+Pvt.+Ltd.'),
	 (144,'','Pavlo Markevych','https://play.google.com/store/apps/developer?id=Pavlo+Markevych'),
	 (145,'','PC Mehanik','https://play.google.com/store/apps/developer?id=PC+Mehanik'),
	 (146,'','Photomath, Inc.','https://play.google.com/store/apps/developer?id=Photomath,+Inc.'),
	 (147,'','Pink Pointer','https://play.google.com/store/apps/developer?id=Pink+Pointer'),
	 (148,'','Pratik Nandha','https://play.google.com/store/apps/developer?id=Pratik+Nandha'),
	 (149,'','Red-Spell','https://play.google.com/store/apps/developer?id=Red-Spell'),
	 (150,'','romeLab','https://play.google.com/store/apps/developer?id=romeLab');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (151,'','SCIMOB','https://play.google.com/store/apps/developer?id=SCIMOB'),
	 (152,'','Sensopia Inc','https://play.google.com/store/apps/developer?id=Sensopia+Inc'),
	 (153,'','Sergey Tropin','https://play.google.com/store/apps/developer?id=Sergey+Tropin'),
	 (154,'','Shadowbiz','https://play.google.com/store/apps/developer?id=Shadowbiz'),
	 (155,'','Shivam.Pandey','https://play.google.com/store/apps/developer?id=Shivam.Pandey'),
	 (156,'','Siebn','https://play.google.com/store/apps/developer?id=Siebn'),
	 (157,'','SimSam','https://play.google.com/store/apps/developer?id=SimSam'),
	 (158,'','Sirvo llc','https://play.google.com/store/apps/developer?id=Sirvo+llc'),
	 (159,'','Statlex','https://play.google.com/store/apps/developer?id=Statlex'),
	 (160,'','team13','https://play.google.com/store/apps/developer?id=team13');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (161,'','Time Killing Machine','https://play.google.com/store/apps/developer?id=Time+Killing+Machine'),
	 (162,'','Tiny Games Srl','https://play.google.com/store/apps/developer?id=Tiny+Games+Srl'),
	 (163,'','Troubi Entertainment','https://play.google.com/store/apps/developer?id=Troubi+Entertainment'),
	 (164,'','Turtle Labs','https://play.google.com/store/apps/developer?id=Turtle+Labs'),
	 (165,'','UFMS Câmpus de Ponta Porã',''),
	 (166,'','Valcour Games','https://play.google.com/store/apps/developer?id=Valcour+Games'),
	 (167,'','Vasilis Charalampakis','https://play.google.com/store/apps/developer?id=Vasilis+Charalampakis'),
	 (168,'','VirtualMaze','https://play.google.com/store/apps/developer?id=VirtualMaze'),
	 (169,'','WeisIA','https://apkpure.com/br/developer/WeisIA'),
	 (170,'obama@imd.ufrn.br','OBAMA - Objetos de Aprendizagem para Matemática','https://obama.imd.ufrn.br');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (171,'','3 Sprockets',''),
	 (172,'','5minLab',''),
	 (173,'','Advance-Media',''),
	 (174,'','Akshay Bhange',''),
	 (175,'','Amanda Rios Ulitska',''),
	 (176,'','Anadreline',''),
	 (177,'','Armor Games',''),
	 (178,'','ARPAplus',''),
	 (179,'','Benjamin Lochmann New Media GmbH',''),
	 (180,'','Christian Göllner','');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (181,'','Cross Reality',''),
	 (182,'','CurryGames',''),
	 (183,'','Desmos Inc',''),
	 (184,'','DJ Mobile',''),
	 (185,'','EstaLo - Estatísticas Lotéricas',''),
	 (186,'','famobix',''),
	 (187,'','FerApps - Mobile Solutions',''),
	 (188,'','free puzzle games',''),
	 (189,'','Funnygames Apps',''),
	 (190,'','GEORGE','');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (191,'','GunjanApps Studios',''),
	 (192,'','Igor Rodrigues Costa',''),
	 (193,'','IMPA',''),
	 (194,'','Jovijano',''),
	 (195,'','JQ Soft',''),
	 (196,'','Kércio Lisboa Sá Cavalcante',''),
	 (197,'','Leap Fitness Group',''),
	 (198,'','Leds Guarapari',''),
	 (199,'','Little Bear Productions',''),
	 (200,'','Lumpty Learning','');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (201,'','MangaX9',''),
	 (202,'','Marcin Gamla',''),
	 (203,'','Mental Lab',''),
	 (204,'','MetalB2 Apps',''),
	 (205,'','Michel Carvajal',''),
	 (206,'','MobillsLabs',''),
	 (207,'','MyScript',''),
	 (208,'','November31',''),
	 (209,'','Orkun2u Studios',''),
	 (210,'','Platonic Games','');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (211,'','Renato Félix da Silva Souza',''),
	 (212,'','Rony C. O. Freitas',''),
	 (213,'','SAT-BOX',''),
	 (214,'','SauzanaProd',''),
	 (215,'','Selfmade Mobile Solutions',''),
	 (216,'','ShadowTree',''),
	 (217,'','Simple Machine',''),
	 (218,'','Slim Cricket',''),
	 (219,'','Socratic',''),
	 (220,'','Solution Developers','');
INSERT INTO public.autor_mantenedor (id,email,nome,site) VALUES
	 (221,'','TeenEinstein',''),
	 (222,'','Tomas Hubalek',''),
	 (223,'','TRE-MT',''),
	 (224,'','Ululab',''),
	 (225,'','WGBN Software House',''),
	 (226,'','Zacharias Games','');
