CREATE TABLE Usuario (
    id int8 NOT NULL,
    nome VARCHAR(255) NOT NULL,
    sobrenome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    role ENUM('ADMIN', 'PADRAO', 'REVISOR') NOT NULL,
    ativo BOOLEAN NOT NULL,
    tipo_cadastro ENUM('PADRAO', 'GOOGLE', 'FACEBOOK') NOT NULL,
    token VARCHAR(255) NOT NULL,
    CONSTRAINT usuario_pk PRIMARY KEY (id)
);

CREATE SEQUENCE sq_usuario_id INCREMENT BY 1
    START WITH 1
    MAXVALUE 99999999999
    MINVALUE 1
    CACHE 10;
