INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(1, 'Infatil', 1);
INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(2, '1º ano', 2);
INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(3, '2º ano', 2);
INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(4, '3º ano',  2);
INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(5, '4º ano',  2);
INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(6, '5º ano', 2);
INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(7, '6º ano',  3);
INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(8, '7º ano', 3);
INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(9, '8º ano', 3);
INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(10, '9º ano', 3);
INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(11, '1º ano', 4);
INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(12, '2º ano', 4);
INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(13, '3º ano', 4);
INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(14, 'EJA', 5);
INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(15, 'ENSINO TÉC/PROF', 6);
INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(16, 'ENSINO SUP', 7);
INSERT INTO ano_ensino (id, nome, nivel_ensino_id) VALUES(17, 'Não identificado', 2);
